const SUPPLEMENTARY_SCALES_INTERPRETATIONS_FEMALE = {
    "A": {  // Anxiety
        "low": "This female reports minimal anxiety symptoms, with appropriate stress responses that return to baseline when stressors diminish. She maintains effective coping strategies for managing routine life challenges without becoming overwhelmed. Her thought patterns remain balanced, considering potential problems without catastrophizing or excessive rumination. Daily functioning across work, relationships, and self-care continues unimpaired by anxiety.",
        "moderate": "This female reports moderately elevated anxiety that occasionally interferes with optimal functioning. She experiences periodic excessive worry that persists beyond appropriate time frames and may be difficult to control. Physical symptoms of anxiety such as muscle tension, sleep disruption, or concentration difficulties are becoming more frequent. While still managing major responsibilities, her anxiety is beginning to create strain in relationships and diminish enjoyment of previously pleasurable activities.",
        "high": "This female reports severe anxiety that significantly impairs her functioning across multiple domains. She experiences persistent, uncontrollable worry that consumes substantial mental energy and interferes with concentration and decision-making. Physical manifestations of anxiety are pronounced, potentially including panic attacks, persistent muscle tension, gastrointestinal distress, and significant sleep disruption. Her anxiety has led to avoidance of anxiety-provoking situations, substantially restricting her activities and relationships. The chronic nature of her anxiety has likely contributed to secondary depression, fatigue, and irritability."
    },
    "R": {  // Repression
        "low": "This female demonstrates minimal psychological defensiveness, with willingness to acknowledge both positive and negative aspects of her experience. She readily admits to normal human flaws, insecurities, and negative emotions without excessive shame or guardedness. Her self-description includes appropriate recognition of personal limitations and mistakes. She shows psychological-mindedness with capacity to reflect on her own motives, emotions, and patterns.",
        "moderate": "This female shows increasing psychological defensiveness and diminished awareness of her own emotional processes. She demonstrates selective attention to positive aspects of experience while minimizing or disavowing negative emotions, particularly anger and resentment. Her self-description emphasizes virtues and strengths with limited acknowledgment of normal human flaws or mistakes. She shows growing reluctance to engage in psychological introspection, preferring concrete explanations for emotional or interpersonal difficulties.",
        "high": "This female demonstrates pronounced psychological defensiveness that significantly limits her self-awareness and capacity for growth. She shows marked inability to recognize or acknowledge negative emotions, particularly anger, resentment, or sexual feelings that conflict with her self-concept as virtuous and proper. Her self-description is highly idealized and lacks the normal human flaws or struggles that create authentic self-portraiture. She demonstrates concrete thinking with minimal psychological-mindedness or introspective capacity. When faced with emotional or interpersonal difficulties, she typically externalizes responsibility or focuses exclusively on physical explanations. This defensive structure significantly impairs her ability to engage productively in psychotherapy or make meaningful psychological changes."
    },
    "Es": {  // Ego Strength
        "low": "This female demonstrates limited psychological resources for managing stress and maintaining stability during challenges. She shows poor frustration tolerance with tendency to become overwhelmed by moderate stressors. Her coping strategies are often maladaptive or insufficient for effective problem resolution. She demonstrates limited capacity for delayed gratification or sustained effort toward long-term goals. Her self-concept lacks coherence and stability across different contexts. Her relationships show patterns of dependency with difficulty maintaining appropriate boundaries. Her emotional regulation is poor, with disproportionate reactions to minor provocations and difficulty returning to baseline after upset.",
        "moderate": "This female demonstrates adequate psychological resources for managing routine stressors, though may become overwhelmed during periods of significant challenge. She shows reasonable frustration tolerance for everyday difficulties but may resort to less adaptive coping when facing major stressors. Her coping strategies are generally effective for common problems but may be insufficient for complex or chronic difficulties. She can delay gratification for moderate periods to achieve important goals. Her self-concept shows basic coherence though may fluctuate somewhat across contexts. Her relationships demonstrate general stability with occasional boundary issues during stress. Her emotional regulation is adequate for routine interactions though may deteriorate during significant conflict or crisis.",
        "high": "This female demonstrates robust psychological resources for managing stress and maintaining stability even during significant challenges. She shows excellent frustration tolerance with capacity to persist through substantial obstacles toward valued goals. Her coping strategies are diverse, flexible, and generally adaptive across various types of problems. She demonstrates strong capacity for delayed gratification in service of meaningful long-term objectives. Her self-concept shows coherence and stability across different contexts while maintaining appropriate flexibility. Her relationships demonstrate healthy interdependence with clear but permeable boundaries. Her emotional regulation is well-developed, with proportionate reactions to provocations and efficient return to baseline after legitimate upset."
    },
    "MAC-R": {  // MacAndrew Alcoholism Scale-Revised
        "low": "This female reports minimal risk factors associated with substance abuse vulnerability. She describes herself as conventional, cautious, and restrained in her approach to pleasure and excitement. She demonstrates strong impulse control and consideration of consequences before acting. Her social relationships are characterized by stability rather than gregariousness or risk-taking. She reports minimal history of behavioral problems, authority conflicts, or legal difficulties. Her approach to life emphasizes planning, responsibility, and adherence to social norms rather than spontaneity or thrill-seeking.",
        "moderate": "This female shows some personality characteristics associated with increased substance abuse vulnerability, though not at the level typically seen in diagnosed substance use disorders. She describes greater enjoyment of excitement, novelty, and social engagement than the average person. Her impulse control is adequate for major decisions but may lapse with smaller temptations. She acknowledges occasional regret following impulsive decisions yet continues similar patterns. While generally functioning within acceptable parameters, her growing prioritization of immediate gratification over long-term consequences may create vulnerability to problematic substance use patterns, particularly in high-risk environments or during periods of significant stress.",
        "high": "This female demonstrates a personality profile strongly associated with substance abuse vulnerability, regardless of whether she currently acknowledges problematic substance use. She describes pronounced enjoyment of excitement, risk-taking, and intense experiences. Her approach to life emphasizes spontaneity and immediate gratification rather than planning or consideration of consequences. She reports significant history of behavioral problems, authority conflicts, or legal difficulties beginning in adolescence or earlier. Her social style is characterized by gregariousness, extraversion, and enjoyment of social dominance. She demonstrates poor frustration tolerance with tendency toward impulsive action when desires are thwarted. This constellation of traits creates substantial vulnerability to developing problematic substance use patterns, particularly in environments where substances are readily available."
    },
    "AAS": {  // Addiction Acknowledgment Scale
        "low": "This female explicitly denies problematic substance use or associated consequences. She reports minimal or no consumption of alcohol or other substances. She denies experiencing tolerance, withdrawal symptoms, or loss of control over substance use. She reports no substance-related interference with major life roles or responsibilities. She denies using substances to manage negative emotions or physical discomfort. She reports no concerns from others about her substance use patterns. She denies engagement in illegal activities related to substance acquisition or use.",
        "moderate": "This female acknowledges some problematic aspects of her substance use while minimizing or rationalizing others. She reports regular substance use that occasionally exceeds her intended limits. She acknowledges some tolerance development though may attribute this to normal adaptation rather than problematic use. She reports occasional interference with responsibilities or relationships due to substance use or recovery from use. She acknowledges sometimes using substances to manage negative emotions or physical discomfort. She reports some expressions of concern from others about her substance use patterns, though typically disagrees with their assessment. She may acknowledge occasional engagement in risky behaviors while using substances.",
        "high": "This female explicitly acknowledges significant problematic substance use and associated consequences. She reports regular substance use that frequently exceeds intended limits with difficulty controlling amount or frequency once started. She acknowledges pronounced tolerance requiring increasing amounts for desired effects. She reports significant interference with major life roles including work performance, relationship quality, or financial stability. She acknowledges regular use of substances to manage negative emotions or physical discomfort. She reports persistent concerns from others about her substance use patterns. She may acknowledge engagement in illegal activities related to substance acquisition or use. This level of acknowledgment typically indicates awareness of a substance use disorder requiring intervention, though not necessarily readiness for treatment."
    },
    "APS": {  // Addiction Potential Scale
        "low": "This female demonstrates minimal personality risk factors associated with substance abuse vulnerability. She describes herself as conventional, cautious, and restrained in her approach to pleasure and excitement. She demonstrates strong impulse control and consideration of consequences before acting. Her social relationships are characterized by stability rather than gregariousness or risk-taking. She reports minimal history of behavioral problems, authority conflicts, or legal difficulties. Her approach to life emphasizes planning, responsibility, and adherence to social norms rather than spontaneity or thrill-seeking. She acknowledges normal human emotions without excessive need to escape or modify her feeling states.",
        "moderate": "This female shows some personality characteristics associated with increased substance abuse vulnerability, though not at the level typically seen in diagnosed substance use disorders. She describes greater enjoyment of excitement, novelty, and social engagement than the average person. Her impulse control is adequate for major decisions but may lapse with smaller temptations. She acknowledges occasional regret following impulsive decisions yet continues similar patterns. She reports some difficulty tolerating negative emotional states, creating potential motivation to use substances for emotional regulation. While generally functioning within acceptable parameters, her personality profile suggests increased vulnerability to developing problematic substance use patterns, particularly in high-risk environments or during periods of significant stress.",
        "high": "This female demonstrates a personality profile strongly associated with substance abuse vulnerability, regardless of whether she currently acknowledges problematic substance use. She describes pronounced enjoyment of excitement, risk-taking, and intense experiences. Her approach to life emphasizes spontaneity and immediate gratification rather than planning or consideration of consequences. She reports significant history of behavioral problems, authority conflicts, or legal difficulties beginning in adolescence or earlier. Her social style is characterized by gregariousness, extraversion, and enjoyment of social dominance. She demonstrates poor frustration tolerance with tendency toward impulsive action when desires are thwarted. She reports substantial difficulty managing negative emotional states without external regulation. This constellation of traits creates substantial vulnerability to developing problematic substance use patterns, particularly in environments where substances are readily available."
    },
    "MDS": {  // Marital Distress Scale
        "low": "This female reports a generally satisfying marital relationship with normal variations in closeness and conflict. She describes effective communication patterns that allow for resolution of disagreements without persistent resentment. She reports mutual respect and appreciation between partners despite awareness of each other's flaws. She describes appropriate balance of togetherness and autonomy within the relationship. Sexual satisfaction is generally positive though may fluctuate with life circumstances. She reports shared decision-making processes that consider both partners' preferences and needs. Financial management shows reasonable agreement about priorities and spending patterns. The relationship demonstrates resilience with capacity to adapt to changing circumstances and recover from occasional conflicts.",
        "moderate": "This female reports increasing marital dissatisfaction that is creating strain though not yet threatening the relationship's viability. She describes communication difficulties with growing patterns of criticism, defensiveness, or withdrawal during conflicts. She reports diminishing expressions of appreciation between partners with greater focus on frustrations and disappointments. She describes increasing emotional distance with less sharing of personal thoughts and feelings. Sexual satisfaction has declined significantly, creating additional relationship tension. She reports more frequent disagreements about decision-making, financial management, or parenting approaches. The relationship shows decreasing resilience with longer recovery periods needed after conflicts and less effective adaptation to changing circumstances.",
        "high": "This female reports severe marital distress that significantly impacts her well-being and may threaten the relationship's continuation. She describes profound communication breakdown characterized by contempt, criticism, defensiveness, and stonewalling. She reports pervasive resentment and lack of appreciation between partners. She describes significant emotional detachment with minimal intimacy or shared positive experiences. Sexual satisfaction is extremely low or absent, contributing to feelings of rejection or alienation. She reports frequent, intense conflicts about major life decisions, finances, or parenting, often without resolution. The relationship demonstrates minimal resilience with inability to recover from conflicts or adapt to changing circumstances. She may be actively considering separation or divorce or feel trapped in an emotionally destructive situation."
    },
    "Ho": {  // Hostility
        "low": "This female reports minimal hostile attitudes or behaviors. She demonstrates appropriate trust in others and doesn't typically expect malevolence or exploitation. She manages frustration effectively without resorting to aggression or passive-aggressive tactics. Her emotional responses to provocation are proportionate and she recovers without lingering resentment. She can acknowledge others' positive qualities without excessive envy or competitiveness. Her relationships are characterized by cooperation and mutual respect rather than cynicism or power struggles.",
        "moderate": "This female is experiencing increasing hostile attitudes and difficulty managing anger. She reports growing cynicism about others' motives and intentions. Her frustration tolerance is diminishing, leading to more frequent irritability and impatience. She describes more frequent resort to passive-aggressive behaviors or verbal arguments when displeased. She acknowledges dwelling on perceived slights with difficulty letting go of resentment. She reports increased competitiveness and envy of others' achievements. While still maintaining control over overt aggression, her growing hostility is creating strain in relationships and diminishing her capacity for positive emotional experiences.",
        "high": "This female's experience is characterized by pervasive hostility and anger that significantly impairs her relationships and well-being. She reports profound cynicism and mistrust, expecting malevolence and exploitation from others. Her frustration tolerance is extremely low, leading to frequent, intense anger outbursts that may include verbal or physical aggression. She describes persistent resentment and bitterness, often ruminating on past injustices or perceived slights. She demonstrates pronounced envy and competitiveness, struggling to acknowledge others' positive qualities or successes. Her relationships are dominated by conflict, power struggles, and emotional distance. This pervasive hostility creates a self-perpetuating cycle of negative interactions that reinforces her cynical worldview and alienates potential sources of support."
    },
    "O-H": {  // Overcontrolled Hostility
        "low": "This female demonstrates appropriate expression of anger and frustration. She can acknowledge and articulate these emotions when they occur without excessive suppression or explosive outbursts. Her responses to provocation are generally proportionate and she recovers without lingering resentment. She doesn't show a pattern of bottling up emotions until they become unmanageable. She can assert her needs and boundaries effectively without resorting to aggression or passive-aggression. Her relationships allow for healthy expression of disagreement and conflict resolution.",
        "moderate": "This female shows increasing tendency to suppress anger and frustration, leading to periodic, disproportionate outbursts. She describes herself as generally patient and easygoing but acknowledges occasional episodes of intense anger that feel out of character. She reports difficulty expressing negative emotions directly, preferring to avoid conflict or withdraw when displeased. This pattern of suppression allows resentment to build until it eventually erupts, often triggered by minor provocations. While she typically regrets these outbursts, she struggles to develop more consistent and adaptive ways of managing anger. Her relationships may be characterized by periods of superficial harmony punctuated by unexpected and intense conflicts.",
        "high": "This female demonstrates a pronounced pattern of overcontrolled hostility, characterized by extreme suppression of anger and frustration that eventually leads to explosive outbursts. She describes herself as exceptionally patient and tolerant, rarely showing outward signs of displeasure even when significantly provoked. However, this chronic suppression allows intense resentment to accumulate, culminating in unpredictable and often destructive episodes of rage. These outbursts may involve verbal or physical aggression that is strikingly out of character with her typical demeanor. She often expresses profound guilt and remorse following these episodes but lacks insight into the underlying dynamic of suppressed anger. This pattern creates significant interpersonal difficulties, as others find her unpredictable and may feel intimidated by the intensity of her occasional outbursts. Effective intervention requires addressing the chronic suppression of anger and developing healthier strategies for emotional expression."
    },
    "Do": {  // Dominance
        "low": "This female demonstrates a preference for deferring to others in decision-making and social interactions. She reports discomfort with leadership roles and avoids situations requiring her to assert authority. She describes herself as accommodating and agreeable, prioritizing harmony over personal influence. She may struggle to express her own opinions or preferences, particularly when they conflict with others'. Her relationships are characterized by following rather than leading, with a tendency to yield to stronger personalities. While this style can foster cooperation, it may also lead to her needs being overlooked or her potential remaining undeveloped.",
        "moderate": "This female shows a balanced approach to leadership and social influence. She can assert her opinions and preferences when appropriate but also values collaboration and others' input. She is comfortable in leadership roles when called upon but doesn't actively seek dominance in all situations. She can make decisions effectively, considering both her own perspectives and relevant information from others. Her relationships demonstrate healthy interdependence, with capacity for both leading and following as appropriate to the context. She can advocate for her needs while respecting others' boundaries.",
        "high": "This female demonstrates a strong preference for leadership and social influence. She actively seeks out positions of authority and enjoys directing others' activities. She is confident in her opinions and readily expresses them, often with persuasive force. She makes decisions decisively and expects others to follow her lead. Her relationships are characterized by taking charge and influencing others' behavior. While this style can be effective in achieving goals and motivating others, it may also lead to interpersonal conflict if she is perceived as overly controlling or dismissive of others' perspectives. She thrives in environments where she can exercise her natural assertiveness and leadership abilities."
    },
    "Re": {  // Social Responsibility
        "low": "This female demonstrates limited adherence to social norms and expectations of responsibility. She reports a history that may include impulsive behavior, rule-breaking, or difficulty fulfilling commitments. Her decision-making shows less consideration of ethical implications or potential negative consequences for others. She may describe herself as unconventional or rebellious, prioritizing personal freedom over social obligations. Her relationships may be characterized by unreliability or difficulty maintaining long-term commitments. She shows less concern for societal standards of conduct and may question the legitimacy of authority figures or established rules.",
        "moderate": "This female shows appropriate adherence to social norms and expectations of responsibility. She generally fulfills commitments and considers ethical implications in her decision-making. She respects rules and authority figures while maintaining capacity for independent judgment. She balances personal desires with social obligations effectively. Her relationships are characterized by reliability and trustworthiness. She demonstrates concern for societal standards of conduct and contributes positively to her community or social groups. She can be depended upon to act responsibly in most situations.",
        "high": "This female demonstrates exceptionally strong adherence to social norms and expectations of responsibility, potentially to the point of over-conformity. She consistently fulfills commitments and prioritizes ethical considerations in all decisions. She shows profound respect for rules, authority figures, and established procedures. She may struggle with ambiguity or situations requiring deviation from accepted standards. Her personal desires are often subordinated to social obligations or the needs of others. Her relationships are characterized by extreme reliability and conscientiousness. While this style fosters trust and stability, it may also limit her flexibility or lead to excessive self-criticism when perceived standards are not met. She may be seen as overly conventional or rigid by others."
    },
    "Mt": {  // College Maladjustment
        "low": "This female reports effective adjustment to the demands of college life. She demonstrates appropriate academic motivation and engagement with her studies. She manages stress related to coursework and exams without significant impairment. Her social adjustment shows capacity for forming positive peer relationships and participating in campus activities. She maintains a healthy balance between academic responsibilities and personal well-being. She reports minimal emotional distress such as anxiety or depression related to her college experience. She shows confidence in her ability to succeed academically and navigate the social environment of college.",
        "moderate": "This female reports some difficulties adjusting to the demands of college life, experiencing moderate stress that occasionally impacts her functioning. She may struggle with academic motivation, concentration, or time management, leading to periodic performance anxiety. Her social adjustment shows some challenges in forming satisfying peer relationships or integrating into campus life. She may experience episodes of anxiety, depression, or homesickness that create emotional distress. While generally managing to meet academic requirements, her overall well-being and enjoyment of the college experience are diminished by these adjustment difficulties. She may benefit from additional support services to enhance her coping strategies and improve her adaptation to college.",
        "high": "This female reports significant difficulties adjusting to the demands of college life, experiencing substantial stress that impairs her academic performance and overall well-being. She struggles significantly with academic motivation, concentration, and time management, leading to persistent performance anxiety and potential academic failure. Her social adjustment is poor, with feelings of isolation, difficulty forming peer relationships, or withdrawal from campus activities. She experiences pronounced emotional distress such as anxiety, depression, or homesickness that significantly impacts her daily functioning. Her capacity to cope with the combined academic and social pressures of college is overwhelmed, potentially leading to consideration of withdrawal or academic leave. She requires substantial support services to address these maladaptive patterns and improve her chances of successful college completion."
    },
    "GM": {  // Masculine Gender Role
        "low": "This female describes herself in terms that align with traditionally feminine gender roles. She emphasizes interpersonal sensitivity, emotional expressiveness, and nurturing qualities. She reports preferences for activities and interests typically associated with femininity. Her problem-solving style may prioritize collaboration and maintaining harmony over direct assertiveness. She may be less comfortable with traditionally masculine traits such as competitiveness, dominance, or emotional restriction. Her self-concept is strongly identified with feminine attributes and values.",
        "moderate": "This female describes herself in terms that integrate both traditionally masculine and feminine gender roles, or shows moderate endorsement of masculine traits. She demonstrates capacity for assertiveness, competitiveness, and emotional control when appropriate, while also valuing interpersonal sensitivity and emotional expressiveness. Her interests and activities may span both traditionally masculine and feminine domains. Her problem-solving style shows flexibility, utilizing both direct action and collaborative approaches. She is comfortable with a range of gender expressions and doesn't rigidly adhere to traditional gender role expectations.",
        "high": "This female describes herself in terms that align strongly with traditionally masculine gender roles. She emphasizes assertiveness, competitiveness, independence, and emotional control. She reports preferences for activities and interests typically associated with masculinity. Her problem-solving style prioritizes direct action, logical analysis, and task-orientation. She may be less comfortable with traditionally feminine traits such as emotional vulnerability, interpersonal sensitivity, or overt nurturing behaviors. Her self-concept is strongly identified with masculine attributes and values. This may reflect genuine personal preferences or adoption of masculine traits as an adaptive strategy in certain environments."
    },
    "GF": {  // Feminine Gender Role
        "low": "This female describes herself in terms that show minimal alignment with traditionally feminine gender roles. She may de-emphasize interpersonal sensitivity, emotional expressiveness, or nurturing qualities. Her preferences for activities and interests may lean away from those typically associated with femininity. Her problem-solving style may prioritize assertiveness, independence, or logical analysis over collaboration and maintaining harmony. She may be less comfortable with traditionally feminine traits and values, potentially seeing them as less effective or desirable. This may reflect genuine personal preferences or rejection of traditional feminine roles due to negative experiences or societal pressures.",
        "moderate": "This female describes herself in terms that integrate both traditionally masculine and feminine gender roles, or shows moderate endorsement of feminine traits. She values interpersonal sensitivity, emotional expressiveness, and nurturing qualities, while also demonstrating capacity for assertiveness and independence. Her interests and activities may span both traditionally feminine and masculine domains. Her problem-solving style shows flexibility, utilizing both collaborative approaches and direct action. She is comfortable with a range of gender expressions and doesn't rigidly adhere to traditional gender role expectations.",
        "high": "This female describes herself in terms that align strongly with traditionally feminine gender roles. She emphasizes interpersonal sensitivity, emotional expressiveness, nurturing qualities, and concern for others' well-being. She reports preferences for activities and interests typically associated with femininity. Her problem-solving style prioritizes collaboration, maintaining harmony, and considering others' feelings. She may be less comfortable with traditionally masculine traits such as overt competitiveness, dominance, or emotional restriction. Her self-concept is strongly identified with feminine attributes and values. This may reflect genuine personal preferences or societal reinforcement of traditional feminine roles."
    },
    "PK": {  // Post-Traumatic Stress Disorder (Keane)
        "low": "This female reports minimal symptoms associated with post-traumatic stress. She denies experiencing or witnessing significant traumatic events. If trauma exposure has occurred, she demonstrates effective coping and resilience without persistent re-experiencing, avoidance, or hyperarousal symptoms. Her emotional regulation remains stable and she maintains positive interpersonal relationships. Her daily functioning is unimpaired by trauma-related sequelae. She reports a sense of safety and control in her environment.",
        "moderate": "This female reports some symptoms associated with post-traumatic stress that are causing moderate distress or functional impairment. She may have experienced or witnessed a significant traumatic event and is now struggling with intrusive memories, nightmares, or flashbacks. She describes some avoidance of trauma-related reminders, leading to restriction in activities or relationships. She reports increased hyperarousal symptoms such as irritability, sleep disturbance, or exaggerated startle response. While still managing major life responsibilities, these PTSD symptoms are diminishing her quality of life and creating emotional strain. She may benefit from trauma-focused intervention to prevent symptom escalation.",
        "high": "This female reports severe and pervasive symptoms associated with post-traumatic stress that significantly impair her functioning across multiple domains. She has likely experienced or witnessed a significant traumatic event and is now overwhelmed by intrusive re-experiencing symptoms such as flashbacks, nightmares, and intense psychological distress when reminded of the trauma. Her avoidance of trauma-related stimuli is pronounced, leading to significant restrictions in daily activities, social withdrawal, and emotional numbing. Hyperarousal symptoms are severe, including persistent irritability, sleep disturbance, hypervigilance, and exaggerated startle response. These PTSD symptoms are causing profound distress and have likely led to secondary problems such as depression, anxiety, or substance use. She requires comprehensive trauma-focused intervention to address these debilitating symptoms and improve her quality of life."
    },
    "PS": {  // Post-Traumatic Stress Disorder (Pennebaker) - Note: This scale is less commonly used and interpretation should be cautious.
        "low": "This female reports minimal psychological or physical symptoms often associated with stress or trauma. She describes a generally positive emotional state and good physical health. She doesn't endorse significant worry, anxiety, or depressive symptoms. Her sleep patterns are regular and she reports adequate energy levels. She denies frequent headaches, gastrointestinal problems, or other somatic complaints that can be stress-related. Her responses suggest effective coping with life stressors and minimal impact from any past traumatic experiences.",
        "moderate": "This female reports a moderate level of psychological or physical symptoms that may be associated with stress or trauma. She acknowledges some worry, anxiety, or depressive feelings that are causing mild to moderate distress. She may experience occasional sleep difficulties, fatigue, or physical discomfort such as headaches or stomach upset. While these symptoms are not debilitating, they suggest an increased level of stress or potential impact from past traumatic experiences. Further exploration of stressors and coping mechanisms may be beneficial.",
        "high": "This female reports a high level of psychological and physical symptoms often associated with significant stress or trauma. She endorses frequent worry, anxiety, or depressive feelings that cause substantial distress and may impair functioning. Her sleep patterns are likely disrupted, and she may experience persistent fatigue. She reports multiple somatic complaints such as chronic headaches, gastrointestinal problems, or other physical discomfort. These responses suggest a significant level of stress, potential impact from past traumatic experiences, or a tendency toward somatization. Comprehensive assessment of stressors, trauma history, and coping resources is indicated."
    }
};

const SUPPLEMENTARY_SCALES_INTERPRETATIONS_MALE = {
    "A": {  // Anxiety
        "low": "This male reports minimal anxiety symptoms, with appropriate stress responses that return to baseline when stressors diminish. He maintains effective coping strategies for managing routine life challenges without becoming overwhelmed. His thought patterns remain balanced, considering potential problems without catastrophizing or excessive rumination. Daily functioning across work, relationships, and self-care continues unimpaired by anxiety.",
        "moderate": "This male reports moderately elevated anxiety that occasionally interferes with optimal functioning. He experiences periodic excessive worry that persists beyond appropriate time frames and may be difficult to control. Physical symptoms of anxiety such as muscle tension, sleep disruption, or concentration difficulties are becoming more frequent. While still managing major responsibilities, his anxiety is beginning to create strain in relationships and diminish enjoyment of previously pleasurable activities.",
        "high": "This male reports severe anxiety that significantly impairs his functioning across multiple domains. He experiences persistent, uncontrollable worry that consumes substantial mental energy and interferes with concentration and decision-making. Physical manifestations of anxiety are pronounced, potentially including panic attacks, persistent muscle tension, gastrointestinal distress, and significant sleep disruption. His anxiety has led to avoidance of anxiety-provoking situations, substantially restricting his activities and relationships. The chronic nature of his anxiety has likely contributed to secondary depression, fatigue, and irritability."
    },
    "R": {  // Repression
        "low": "This male demonstrates minimal psychological defensiveness, with willingness to acknowledge both positive and negative aspects of his experience. He readily admits to normal human flaws, insecurities, and negative emotions without excessive shame or guardedness. His self-description includes appropriate recognition of personal limitations and mistakes. He shows psychological-mindedness with capacity to reflect on his own motives, emotions, and patterns.",
        "moderate": "This male shows increasing psychological defensiveness and diminished awareness of his own emotional processes. He demonstrates selective attention to positive aspects of experience while minimizing or disavowing negative emotions, particularly vulnerability or sadness. His self-description emphasizes strengths and achievements with limited acknowledgment of normal human flaws or mistakes. He shows growing reluctance to engage in psychological introspection, preferring action-oriented or concrete explanations for emotional or interpersonal difficulties.",
        "high": "This male demonstrates pronounced psychological defensiveness that significantly limits his self-awareness and capacity for growth. He shows marked inability to recognize or acknowledge vulnerable emotions such as sadness, fear, or dependency, which may conflict with his masculine self-concept. His self-description is highly idealized, emphasizing strength, independence, and control, while lacking acknowledgment of normal human flaws or struggles. He demonstrates concrete thinking with minimal psychological-mindedness or introspective capacity. When faced with emotional or interpersonal difficulties, he typically externalizes responsibility, focuses on practical solutions, or withdraws emotionally. This defensive structure significantly impairs his ability to engage productively in psychotherapy or make meaningful psychological changes, particularly in areas requiring emotional vulnerability."
    },
    "Es": {  // Ego Strength
        "low": "This male demonstrates limited psychological resources for managing stress and maintaining stability during challenges. He shows poor frustration tolerance with tendency to become overwhelmed by moderate stressors. His coping strategies are often maladaptive or insufficient for effective problem resolution. He demonstrates limited capacity for delayed gratification or sustained effort toward long-term goals. His self-concept lacks coherence and stability across different contexts. His relationships may show patterns of avoidance or superficiality with difficulty maintaining genuine intimacy. His emotional regulation is poor, with disproportionate reactions to minor provocations and difficulty returning to baseline after upset, potentially manifesting as irritability or withdrawal.",
        "moderate": "This male demonstrates adequate psychological resources for managing routine stressors, though may become overwhelmed during periods of significant challenge. He shows reasonable frustration tolerance for everyday difficulties but may resort to less adaptive coping when facing major stressors. His coping strategies are generally effective for common problems but may be insufficient for complex or chronic difficulties. He can delay gratification for moderate periods to achieve important goals. His self-concept shows basic coherence though may fluctuate somewhat across contexts. His relationships demonstrate general stability with capacity for appropriate intimacy, though may become strained during stress. His emotional regulation is adequate for routine interactions though may deteriorate during significant conflict or crisis, potentially manifesting as increased irritability or avoidance.",
        "high": "This male demonstrates robust psychological resources for managing stress and maintaining stability even during significant challenges. He shows excellent frustration tolerance with capacity to persist through substantial obstacles toward valued goals. His coping strategies are diverse, flexible, and generally adaptive across various types of problems. He demonstrates strong capacity for delayed gratification in service of meaningful long-term objectives. His self-concept shows coherence and stability across different contexts while maintaining appropriate flexibility. His relationships demonstrate healthy interdependence with capacity for genuine intimacy and appropriate boundaries. His emotional regulation is well-developed, with proportionate reactions to provocations and efficient return to baseline after legitimate upset. He projects confidence and resilience in facing life's demands."
    },
    "MAC-R": {  // MacAndrew Alcoholism Scale-Revised
        "low": "This male reports minimal risk factors associated with substance abuse vulnerability. He describes himself as conventional, cautious, and restrained in his approach to pleasure and excitement. He demonstrates strong impulse control and consideration of consequences before acting. His social relationships are characterized by stability rather than gregariousness or risk-taking. He reports minimal history of behavioral problems, authority conflicts, or legal difficulties. His approach to life emphasizes planning, responsibility, and adherence to social norms rather than spontaneity or thrill-seeking.",
        "moderate": "This male shows some personality characteristics associated with increased substance abuse vulnerability, though not at the level typically seen in diagnosed substance use disorders. He describes greater enjoyment of excitement, novelty, and social engagement than the average person. His impulse control is adequate for major decisions but may lapse with smaller temptations. He acknowledges occasional regret following impulsive decisions yet continues similar patterns. While generally functioning within acceptable parameters, his growing prioritization of immediate gratification over long-term consequences may create vulnerability to problematic substance use patterns, particularly in high-risk environments or during periods of significant stress.",
        "high": "This male demonstrates a personality profile strongly associated with substance abuse vulnerability, regardless of whether he currently acknowledges problematic substance use. He describes pronounced enjoyment of excitement, risk-taking, and intense experiences. His approach to life emphasizes spontaneity and immediate gratification rather than planning or consideration of consequences. He reports significant history of behavioral problems, authority conflicts, or legal difficulties beginning in adolescence or earlier. His social style is characterized by gregariousness, extraversion, and enjoyment of social dominance. He demonstrates poor frustration tolerance with tendency toward impulsive action when desires are thwarted. This constellation of traits creates substantial vulnerability to developing problematic substance use patterns, particularly in environments where substances are readily available."
    },
    "AAS": {  // Addiction Acknowledgment Scale
        "low": "This male explicitly denies problematic substance use or associated consequences. He reports minimal or no consumption of alcohol or other substances. He denies experiencing tolerance, withdrawal symptoms, or loss of control over substance use. He reports no substance-related interference with major life roles or responsibilities. He denies using substances to manage negative emotions or physical discomfort. He reports no concerns from others about his substance use patterns. He denies engagement in illegal activities related to substance acquisition or use.",
        "moderate": "This male acknowledges some problematic aspects of his substance use while minimizing or rationalizing others. He reports regular substance use that occasionally exceeds his intended limits. He acknowledges some tolerance development though may attribute this to normal adaptation rather than problematic use. He reports occasional interference with responsibilities or relationships due to substance use or recovery from use. He acknowledges sometimes using substances to manage negative emotions or physical discomfort. He reports some expressions of concern from others about his substance use patterns, though typically disagrees with their assessment. He may acknowledge occasional engagement in risky behaviors while using substances.",
        "high": "This male explicitly acknowledges significant problematic substance use and associated consequences. He reports regular substance use that frequently exceeds intended limits with difficulty controlling amount or frequency once started. He acknowledges pronounced tolerance requiring increasing amounts for desired effects. He reports significant interference with major life roles including work performance, relationship quality, or financial stability. He acknowledges regular use of substances to manage negative emotions or physical discomfort. He reports persistent concerns from others about his substance use patterns. He may acknowledge engagement in illegal activities related to substance acquisition or use. This level of acknowledgment typically indicates awareness of a substance use disorder requiring intervention, though not necessarily readiness for treatment."
    },
    "APS": {  // Addiction Potential Scale
        "low": "This male demonstrates minimal personality risk factors associated with substance abuse vulnerability. He describes himself as conventional, cautious, and restrained in his approach to pleasure and excitement. He demonstrates strong impulse control and consideration of consequences before acting. His social relationships are characterized by stability rather than gregariousness or risk-taking. He reports minimal history of behavioral problems, authority conflicts, or legal difficulties. His approach to life emphasizes planning, responsibility, and adherence to social norms rather than spontaneity or thrill-seeking. He acknowledges normal human emotions without excessive need to escape or modify his feeling states.",
        "moderate": "This male shows some personality characteristics associated with increased substance abuse vulnerability, though not at the level typically seen in diagnosed substance use disorders. He describes greater enjoyment of excitement, novelty, and social engagement than the average person. His impulse control is adequate for major decisions but may lapse with smaller temptations. He acknowledges occasional regret following impulsive decisions yet continues similar patterns. He reports some difficulty tolerating negative emotional states, creating potential motivation to use substances for emotional regulation. While generally functioning within acceptable parameters, his personality profile suggests increased vulnerability to developing problematic substance use patterns, particularly in high-risk environments or during periods of significant stress.",
        "high": "This male demonstrates a personality profile strongly associated with substance abuse vulnerability, regardless of whether he currently acknowledges problematic substance use. He describes pronounced enjoyment of excitement, risk-taking, and intense experiences. His approach to life emphasizes spontaneity and immediate gratification rather than planning or consideration of consequences. He reports significant history of behavioral problems, authority conflicts, or legal difficulties beginning in adolescence or earlier. His social style is characterized by gregariousness, extraversion, and enjoyment of social dominance. He demonstrates poor frustration tolerance with tendency toward impulsive action when desires are thwarted. He reports substantial difficulty managing negative emotional states without external regulation. This constellation of traits creates substantial vulnerability to developing problematic substance use patterns, particularly in environments where substances are readily available."
    },
    "MDS": {  // Marital Distress Scale
        "low": "This male reports a generally satisfying marital relationship with normal variations in closeness and conflict. He describes effective communication patterns that allow for resolution of disagreements without persistent resentment. He reports mutual respect and appreciation between partners despite awareness of each other's flaws. He describes appropriate balance of togetherness and autonomy within the relationship. Sexual satisfaction is generally positive though may fluctuate with life circumstances. He reports shared decision-making processes that consider both partners' preferences and needs. Financial management shows reasonable agreement about priorities and spending patterns. The relationship demonstrates resilience with capacity to adapt to changing circumstances and recover from occasional conflicts.",
        "moderate": "This male reports increasing marital dissatisfaction that is creating strain though not yet threatening the relationship's viability. He describes communication difficulties with growing patterns of criticism, defensiveness, or withdrawal during conflicts. He reports diminishing expressions of appreciation between partners with greater focus on frustrations and disappointments. He describes increasing emotional distance with less sharing of personal thoughts and feelings. Sexual satisfaction has declined significantly, creating additional relationship tension. He reports more frequent disagreements about decision-making, financial management, or parenting approaches. The relationship shows decreasing resilience with longer recovery periods needed after conflicts and less effective adaptation to changing circumstances.",
        "high": "This male reports severe marital distress that significantly impacts his well-being and may threaten the relationship's continuation. He describes profound communication breakdown characterized by contempt, criticism, defensiveness, and stonewalling. He reports pervasive resentment and lack of appreciation between partners. He describes significant emotional detachment with minimal intimacy or shared positive experiences. Sexual satisfaction is extremely low or absent, contributing to feelings of rejection or alienation. He reports frequent, intense conflicts about major life decisions, finances, or parenting, often without resolution. The relationship demonstrates minimal resilience with inability to recover from conflicts or adapt to changing circumstances. He may be actively considering separation or divorce or feel trapped in an emotionally destructive situation."
    },
    "Ho": {  // Hostility
        "low": "This male reports minimal hostile attitudes or behaviors. He demonstrates appropriate trust in others and doesn't typically expect malevolence or exploitation. He manages frustration effectively without resorting to aggression or passive-aggressive tactics. His emotional responses to provocation are proportionate and he recovers without lingering resentment. He can acknowledge others' positive qualities without excessive envy or competitiveness. His relationships are characterized by cooperation and mutual respect rather than cynicism or power struggles.",
        "moderate": "This male is experiencing increasing hostile attitudes and difficulty managing anger. He reports growing cynicism about others' motives and intentions. His frustration tolerance is diminishing, leading to more frequent irritability and impatience. He describes more frequent resort to passive-aggressive behaviors or verbal arguments when displeased. He acknowledges dwelling on perceived slights with difficulty letting go of resentment. He reports increased competitiveness and envy of others' achievements. While still maintaining control over overt aggression, his growing hostility is creating strain in relationships and diminishing his capacity for positive emotional experiences.",
        "high": "This male's experience is characterized by pervasive hostility and anger that significantly impairs his relationships and well-being. He reports profound cynicism and mistrust, expecting malevolence and exploitation from others. His frustration tolerance is extremely low, leading to frequent, intense anger outbursts that may include verbal or physical aggression. He describes persistent resentment and bitterness, often ruminating on past injustices or perceived slights. He demonstrates pronounced envy and competitiveness, struggling to acknowledge others' positive qualities or successes. His relationships are dominated by conflict, power struggles, and emotional distance. This pervasive hostility creates a self-perpetuating cycle of negative interactions that reinforces his cynical worldview and alienates potential sources of support."
    },
    "O-H": {  // Overcontrolled Hostility
        "low": "This male demonstrates appropriate expression of anger and frustration. He can acknowledge and articulate these emotions when they occur without excessive suppression or explosive outbursts. His responses to provocation are generally proportionate and he recovers without lingering resentment. He doesn't show a pattern of bottling up emotions until they become unmanageable. He can assert his needs and boundaries effectively without resorting to aggression or passive-aggression. His relationships allow for healthy expression of disagreement and conflict resolution.",
        "moderate": "This male shows increasing tendency to suppress anger and frustration, leading to periodic, disproportionate outbursts. He describes himself as generally patient and easygoing but acknowledges occasional episodes of intense anger that feel out of character. He reports difficulty expressing negative emotions directly, preferring to avoid conflict or withdraw when displeased. This pattern of suppression allows resentment to build until it eventually erupts, often triggered by minor provocations. While he typically regrets these outbursts, he struggles to develop more consistent and adaptive ways of managing anger. His relationships may be characterized by periods of superficial harmony punctuated by unexpected and intense conflicts.",
        "high": "This male demonstrates a pronounced pattern of overcontrolled hostility, characterized by extreme suppression of anger and frustration that eventually leads to explosive outbursts. He describes himself as exceptionally patient and tolerant, rarely showing outward signs of displeasure even when significantly provoked. However, this chronic suppression allows intense resentment to accumulate, culminating in unpredictable and often destructive episodes of rage. These outbursts may involve verbal or physical aggression that is strikingly out of character with his typical demeanor. He often expresses profound guilt and remorse following these episodes but lacks insight into the underlying dynamic of suppressed anger. This pattern creates significant interpersonal difficulties, as others find him unpredictable and may feel intimidated by the intensity of his occasional outbursts. Effective intervention requires addressing the chronic suppression of anger and developing healthier strategies for emotional expression."
    },
    "Do": {  // Dominance
        "low": "This male demonstrates a preference for deferring to others in decision-making and social interactions. He reports discomfort with leadership roles and avoids situations requiring him to assert authority. He describes himself as accommodating and agreeable, prioritizing harmony over personal influence. He may struggle to express his own opinions or preferences, particularly when they conflict with others'. His relationships are characterized by following rather than leading, with a tendency to yield to stronger personalities. While this style can foster cooperation, it may also lead to his needs being overlooked or his potential remaining undeveloped.",
        "moderate": "This male shows a balanced approach to leadership and social influence. He can assert his opinions and preferences when appropriate but also values collaboration and others' input. He is comfortable in leadership roles when called upon but doesn't actively seek dominance in all situations. He can make decisions effectively, considering both his own perspectives and relevant information from others. His relationships demonstrate healthy interdependence, with capacity for both leading and following as appropriate to the context. He can advocate for his needs while respecting others' boundaries.",
        "high": "This male demonstrates a strong preference for leadership and social influence. He actively seeks out positions of authority and enjoys directing others' activities. He is confident in his opinions and readily expresses them, often with persuasive force. He makes decisions decisively and expects others to follow his lead. His relationships are characterized by taking charge and influencing others' behavior. While this style can be effective in achieving goals and motivating others, it may also lead to interpersonal conflict if he is perceived as overly controlling or dismissive of others' perspectives. He thrives in environments where he can exercise his natural assertiveness and leadership abilities."
    },
    "Re": {  // Social Responsibility
        "low": "This male demonstrates limited adherence to social norms and expectations of responsibility. He reports a history that may include impulsive behavior, rule-breaking, or difficulty fulfilling commitments. His decision-making shows less consideration of ethical implications or potential negative consequences for others. He may describe himself as unconventional or rebellious, prioritizing personal freedom over social obligations. His relationships may be characterized by unreliability or difficulty maintaining long-term commitments. He shows less concern for societal standards of conduct and may question the legitimacy of authority figures or established rules.",
        "moderate": "This male shows appropriate adherence to social norms and expectations of responsibility. He generally fulfills commitments and considers ethical implications in his decision-making. He respects rules and authority figures while maintaining capacity for independent judgment. He balances personal desires with social obligations effectively. His relationships are characterized by reliability and trustworthiness. He demonstrates concern for societal standards of conduct and contributes positively to his community or social groups. He can be depended upon to act responsibly in most situations.",
        "high": "This male demonstrates exceptionally strong adherence to social norms and expectations of responsibility, potentially to the point of over-conformity. He consistently fulfills commitments and prioritizes ethical considerations in all decisions. He shows profound respect for rules, authority figures, and established procedures. He may struggle with ambiguity or situations requiring deviation from accepted standards. His personal desires are often subordinated to social obligations or the needs of others. His relationships are characterized by extreme reliability and conscientiousness. While this style fosters trust and stability, it may also limit his flexibility or lead to excessive self-criticism when perceived standards are not met. He may be seen as overly conventional or rigid by others."
    },
    "Mt": {  // College Maladjustment
        "low": "This male reports effective adjustment to the demands of college life. He demonstrates appropriate academic motivation and engagement with his studies. He manages stress related to coursework and exams without significant impairment. His social adjustment shows capacity for forming positive peer relationships and participating in campus activities. He maintains a healthy balance between academic responsibilities and personal well-being. He reports minimal emotional distress such as anxiety or depression related to his college experience. He shows confidence in his ability to succeed academically and navigate the social environment of college.",
        "moderate": "This male reports some difficulties adjusting to the demands of college life, experiencing moderate stress that occasionally impacts his functioning. He may struggle with academic motivation, concentration, or time management, leading to periodic performance anxiety. His social adjustment shows some challenges in forming satisfying peer relationships or integrating into campus life. He may experience episodes of anxiety, depression, or homesickness that create emotional distress. While generally managing to meet academic requirements, his overall well-being and enjoyment of the college experience are diminished by these adjustment difficulties. He may benefit from additional support services to enhance his coping strategies and improve his adaptation to college.",
        "high": "This male reports significant difficulties adjusting to the demands of college life, experiencing substantial stress that impairs his academic performance and overall well-being. He struggles significantly with academic motivation, concentration, and time management, leading to persistent performance anxiety and potential academic failure. His social adjustment is poor, with feelings of isolation, difficulty forming peer relationships, or withdrawal from campus activities. He experiences pronounced emotional distress such as anxiety, depression, or homesickness that significantly impacts his daily functioning. His capacity to cope with the combined academic and social pressures of college is overwhelmed, potentially leading to consideration of withdrawal or academic leave. He requires substantial support services to address these maladaptive patterns and improve his chances of successful college completion."
    },
    "GM": {  // Masculine Gender Role
        "low": "This male describes himself in terms that show minimal alignment with traditionally masculine gender roles. He may de-emphasize assertiveness, competitiveness, or emotional control. His preferences for activities and interests may lean away from those typically associated with masculinity. His problem-solving style may prioritize collaboration or interpersonal sensitivity over direct action or task-orientation. He may be more comfortable with emotional expressiveness or vulnerability than is typical for traditional masculinity. This may reflect genuine personal preferences or rejection of rigid masculine stereotypes.",
        "moderate": "This male describes himself in terms that integrate both traditionally masculine and feminine gender roles, or shows moderate endorsement of masculine traits. He demonstrates capacity for assertiveness, competitiveness, and emotional control when appropriate, while also valuing interpersonal sensitivity and emotional expressiveness. His interests and activities may span both traditionally masculine and feminine domains. His problem-solving style shows flexibility, utilizing both direct action and collaborative approaches. He is comfortable with a range of gender expressions and doesn't rigidly adhere to traditional gender role expectations.",
        "high": "This male describes himself in terms that align strongly with traditionally masculine gender roles. He emphasizes assertiveness, competitiveness, independence, emotional control, and task-orientation. He reports preferences for activities and interests typically associated with masculinity. His problem-solving style prioritizes direct action, logical analysis, and achieving dominance or control. He may be less comfortable with emotional vulnerability, interpersonal sensitivity, or overt nurturing behaviors. His self-concept is strongly identified with masculine attributes and values. This may reflect genuine personal preferences or societal reinforcement of traditional masculine roles."
    },
    "GF": {  // Feminine Gender Role
        "low": "This male describes himself in terms that show minimal alignment with traditionally feminine gender roles. He emphasizes assertiveness, independence, and emotional control over interpersonal sensitivity or nurturing qualities. His preferences for activities and interests likely lean strongly toward those typically associated with masculinity. His problem-solving style prioritizes logical analysis and direct action rather than collaboration or considering others' feelings. He may be uncomfortable with emotional vulnerability or overt expressions of dependency. This reflects a strong identification with traditional masculine attributes and a rejection of traditionally feminine ones.",
        "moderate": "This male describes himself in terms that integrate both traditionally masculine and feminine gender roles, or shows moderate endorsement of feminine traits. He values interpersonal sensitivity, emotional expressiveness, and nurturing qualities, while also demonstrating capacity for assertiveness and independence. His interests and activities may span both traditionally feminine and masculine domains. His problem-solving style shows flexibility, utilizing both collaborative approaches and direct action. He is comfortable with a range of gender expressions and doesn't rigidly adhere to traditional gender role expectations, suggesting psychological androgyny or a departure from rigid masculine norms.",
        "high": "This male describes himself in terms that align strongly with traditionally feminine gender roles, which is atypical for men in most Western cultures. He emphasizes interpersonal sensitivity, emotional expressiveness, nurturing qualities, and concern for others' well-being. He reports preferences for activities and interests typically associated with femininity. His problem-solving style prioritizes collaboration, maintaining harmony, and considering others' feelings. He may be less comfortable with traditionally masculine traits such as overt competitiveness, dominance, or emotional restriction. His self-concept is strongly identified with feminine attributes and values. This unusual endorsement for a male may reflect genuine personal preferences, a unique upbringing, or specific subcultural influences and warrants careful consideration in the context of his overall personality and adjustment."
    },
    "PK": {  // Post-Traumatic Stress Disorder (Keane)
        "low": "This male reports minimal symptoms associated with post-traumatic stress. He denies experiencing or witnessing significant traumatic events. If trauma exposure has occurred, he demonstrates effective coping and resilience without persistent re-experiencing, avoidance, or hyperarousal symptoms. His emotional regulation remains stable and he maintains positive interpersonal relationships. His daily functioning is unimpaired by trauma-related sequelae. He reports a sense of safety and control in his environment.",
        "moderate": "This male reports some symptoms associated with post-traumatic stress that are causing moderate distress or functional impairment. He may have experienced or witnessed a significant traumatic event and is now struggling with intrusive memories, nightmares, or flashbacks. He describes some avoidance of trauma-related reminders, leading to restriction in activities or relationships. He reports increased hyperarousal symptoms such as irritability, sleep disturbance, or exaggerated startle response. While still managing major life responsibilities, these PTSD symptoms are diminishing his quality of life and creating emotional strain. He may benefit from trauma-focused intervention to prevent symptom escalation.",
        "high": "This male reports severe and pervasive symptoms associated with post-traumatic stress that significantly impair his functioning across multiple domains. He has likely experienced or witnessed a significant traumatic event and is now overwhelmed by intrusive re-experiencing symptoms such as flashbacks, nightmares, and intense psychological distress when reminded of the trauma. His avoidance of trauma-related stimuli is pronounced, leading to significant restrictions in daily activities, social withdrawal, and emotional numbing. Hyperarousal symptoms are severe, including persistent irritability, sleep disturbance, hypervigilance, and exaggerated startle response. These PTSD symptoms are causing profound distress and have likely led to secondary problems such as depression, anxiety, or substance use. He requires comprehensive trauma-focused intervention to address these debilitating symptoms and improve his quality of life."
    },
    "PS": {  // Post-Traumatic Stress Disorder (Pennebaker) - Note: This scale is less commonly used and interpretation should be cautious.
        "low": "This male reports minimal psychological or physical symptoms often associated with stress or trauma. He describes a generally positive emotional state and good physical health. He doesn't endorse significant worry, anxiety, or depressive symptoms. His sleep patterns are regular and he reports adequate energy levels. He denies frequent headaches, gastrointestinal problems, or other somatic complaints that can be stress-related. His responses suggest effective coping with life stressors and minimal impact from any past traumatic experiences.",
        "moderate": "This male reports a moderate level of psychological or physical symptoms that may be associated with stress or trauma. He acknowledges some worry, anxiety, or depressive feelings that are causing mild to moderate distress. He may experience occasional sleep difficulties, fatigue, or physical discomfort such as headaches or stomach upset. While these symptoms are not debilitating, they suggest an increased level of stress or potential impact from past traumatic experiences. Further exploration of stressors and coping mechanisms may be beneficial.",
        "high": "This male reports a high level of psychological and physical symptoms often associated with significant stress or trauma. He endorses frequent worry, anxiety, or depressive feelings that cause substantial distress and may impair functioning. His sleep patterns are likely disrupted, and he may experience persistent fatigue. He reports multiple somatic complaints such as chronic headaches, gastrointestinal problems, or other physical discomfort. These responses suggest a significant level of stress, potential impact from past traumatic experiences, or a tendency toward somatization. Comprehensive assessment of stressors, trauma history, and coping resources is indicated."
    }
};
