var SUPPLEMENTARY_SCALES_FEMALE_JS = {
    "A": {
        "low": "This female reports minimal anxiety symptoms, with appropriate stress responses that return to baseline when stressors diminish. She maintains effective coping strategies for managing routine life challenges without becoming overwhelmed. Her thought patterns remain balanced, considering potential problems without catastrophizing or excessive rumination. Daily functioning across work, relationships, and self-care continues unimpaired by anxiety.",
        "moderate": "This female reports moderately elevated anxiety that occasionally interferes with optimal functioning. She experiences periodic excessive worry that persists beyond appropriate time frames and may be difficult to control. Physical symptoms of anxiety such as muscle tension, sleep disruption, or concentration difficulties are becoming more frequent. While still managing major responsibilities, her anxiety is beginning to create strain in relationships and diminish enjoyment of previously pleasurable activities.",
        "high": "This female reports severe anxiety that significantly impairs her functioning across multiple domains. She experiences persistent, uncontrollable worry that consumes substantial mental energy and interferes with concentration and decision-making. Physical manifestations of anxiety are pronounced, potentially including panic attacks, persistent muscle tension, gastrointestinal distress, and significant sleep disruption. Her anxiety has led to avoidance of anxiety-provoking situations, substantially restricting her activities and relationships. The chronic nature of her anxiety has likely contributed to secondary depression, fatigue, and irritability."
    },
    "R": {
        "low": "This female demonstrates minimal psychological defensiveness, with willingness to acknowledge both positive and negative aspects of her experience. She readily admits to normal human flaws, insecurities, and negative emotions without excessive shame or guardedness. Her self-description includes appropriate recognition of personal limitations and mistakes. She shows psychological-mindedness with capacity to reflect on her own motives, emotions, and patterns.",
        "moderate": "This female shows increasing psychological defensiveness and diminished awareness of her own emotional processes. She demonstrates selective attention to positive aspects of experience while minimizing or disavowing negative emotions, particularly anger and resentment. Her self-description emphasizes virtues and strengths with limited acknowledgment of normal human flaws or mistakes. She shows growing reluctance to engage in psychological introspection, preferring concrete explanations for emotional or interpersonal difficulties.",
        "high": "This female demonstrates pronounced psychological defensiveness that significantly limits her self-awareness and capacity for growth. She shows marked inability to recognize or acknowledge negative emotions, particularly anger, resentment, or sexual feelings that conflict with her self-concept as virtuous and proper. Her self-description is highly idealized and lacks the normal human flaws or struggles that create authentic self-portraiture. She demonstrates concrete thinking with minimal psychological-mindedness or introspective capacity. When faced with emotional or interpersonal difficulties, she typically externalizes responsibility or focuses exclusively on physical explanations. This defensive structure significantly impairs her ability to engage productively in psychotherapy or make meaningful psychological changes."
    },
    "Es": {
        "low": "This female demonstrates limited psychological resources for managing stress and maintaining stability during challenges. She shows poor frustration tolerance with tendency to become overwhelmed by moderate stressors. Her coping strategies are often maladaptive or insufficient for effective problem resolution. She demonstrates limited capacity for delayed gratification or sustained effort toward long-term goals. Her self-concept lacks coherence and stability across different contexts. Her relationships show patterns of dependency with difficulty maintaining appropriate boundaries. Her emotional regulation is poor, with disproportionate reactions to minor provocations and difficulty returning to baseline after upset.",
        "moderate": "This female demonstrates adequate psychological resources for managing routine stressors, though may become overwhelmed during periods of significant challenge. She shows reasonable frustration tolerance for everyday difficulties but may resort to less adaptive coping when facing major stressors. Her coping strategies are generally effective for common problems but may be insufficient for complex or chronic difficulties. She can delay gratification for moderate periods to achieve important goals. Her self-concept shows basic coherence though may fluctuate somewhat across contexts. Her relationships demonstrate general stability with occasional boundary issues during stress. Her emotional regulation is adequate for routine interactions though may deteriorate during significant conflict or crisis.",
        "high": "This female demonstrates robust psychological resources for managing stress and maintaining stability even during significant challenges. She shows excellent frustration tolerance with capacity to persist through substantial obstacles toward valued goals. Her coping strategies are diverse, flexible, and generally adaptive across various types of problems. She demonstrates strong capacity for delayed gratification in service of meaningful long-term objectives. Her self-concept shows coherence and stability across different contexts while maintaining appropriate flexibility. Her relationships demonstrate healthy interdependence with clear but permeable boundaries. Her emotional regulation is well-developed, with proportionate reactions to provocations and efficient return to baseline after legitimate upset."
    },
    "MAC-R": {
        "low": "This female reports minimal risk factors associated with substance abuse vulnerability. She describes herself as conventional, cautious, and restrained in her approach to pleasure and excitement. She demonstrates strong impulse control and consideration of consequences before acting. Her social relationships are characterized by stability rather than gregariousness or risk-taking. She reports minimal history of behavioral problems, authority conflicts, or legal difficulties. Her approach to life emphasizes planning, responsibility, and adherence to social norms rather than spontaneity or thrill-seeking.",
        "moderate": "This female shows some personality characteristics associated with increased substance abuse vulnerability, though not at the level typically seen in diagnosed substance use disorders. She describes greater enjoyment of excitement, novelty, and social engagement than the average person. Her impulse control is adequate for major decisions but may lapse with smaller temptations. She acknowledges occasional regret following impulsive decisions yet continues similar patterns. While generally functioning within acceptable parameters, her growing prioritization of immediate gratification over long-term consequences may create vulnerability to problematic substance use patterns, particularly in high-risk environments or during periods of significant stress.",
        "high": "This female demonstrates a personality profile strongly associated with substance abuse vulnerability, regardless of whether she currently acknowledges problematic substance use. She describes pronounced enjoyment of excitement, risk-taking, and intense experiences. Her approach to life emphasizes spontaneity and immediate gratification rather than planning or consideration of consequences. She reports significant history of behavioral problems, authority conflicts, or legal difficulties beginning in adolescence or earlier. Her social style is characterized by gregariousness, extraversion, and enjoyment of social dominance. She demonstrates poor frustration tolerance with tendency toward impulsive action when desires are thwarted. This constellation of traits creates substantial vulnerability to developing problematic substance use patterns, particularly in environments where substances are readily available."
    },
    "AAS": {
        "low": "This female explicitly denies problematic substance use or associated consequences. She reports minimal or no consumption of alcohol or other substances. She denies experiencing tolerance, withdrawal symptoms, or loss of control over substance use. She reports no substance-related interference with major life roles or responsibilities. She denies using substances to manage negative emotions or physical discomfort. She reports no concerns from others about her substance use patterns. She denies engagement in illegal activities related to substance acquisition or use.",
        "moderate": "This female acknowledges some problematic aspects of her substance use while minimizing or rationalizing others. She reports regular substance use that occasionally exceeds her intended limits. She acknowledges some tolerance development though may attribute this to normal adaptation rather than problematic use. She reports occasional interference with responsibilities or relationships due to substance use or recovery from use. She acknowledges sometimes using substances to manage negative emotions or physical discomfort. She reports some expressions of concern from others about her substance use patterns, though typically disagrees with their assessment. She may acknowledge occasional engagement in risky behaviors while using substances.",
        "high": "This female explicitly acknowledges significant problematic substance use and associated consequences. She reports regular substance use that frequently exceeds intended limits with difficulty controlling amount or frequency once started. She acknowledges pronounced tolerance requiring increasing amounts for desired effects. She reports significant interference with major life roles including work performance, relationship quality, or financial stability. She acknowledges regular use of substances to manage negative emotions or physical discomfort. She reports persistent concerns from others about her substance use patterns. She may acknowledge engagement in illegal activities related to substance acquisition or use. This level of acknowledgment typically indicates awareness of a substance use disorder requiring intervention, though not necessarily readiness for treatment."
    },
    "APS": {
        "low": "This female demonstrates minimal personality risk factors associated with substance abuse vulnerability. She describes herself as conventional, cautious, and restrained in her approach to pleasure and excitement. She demonstrates strong impulse control and consideration of consequences before acting. Her social relationships are characterized by stability rather than gregariousness or risk-taking. She reports minimal history of behavioral problems, authority conflicts, or legal difficulties. Her approach to life emphasizes planning, responsibility, and adherence to social norms rather than spontaneity or thrill-seeking. She acknowledges normal human emotions without excessive need to escape or modify her feeling states.",
        "moderate": "This female shows some personality characteristics associated with increased substance abuse vulnerability, though not at the level typically seen in diagnosed substance use disorders. She describes greater enjoyment of excitement, novelty, and social engagement than the average person. Her impulse control is adequate for major decisions but may lapse with smaller temptations. She acknowledges occasional regret following impulsive decisions yet continues similar patterns. She reports some difficulty tolerating negative emotional states, creating potential motivation to use substances for emotional regulation. While generally functioning within acceptable parameters, her personality profile suggests increased vulnerability to developing problematic substance use patterns, particularly in high-risk environments or during periods of significant stress.",
        "high": "This female demonstrates a personality profile strongly associated with substance abuse vulnerability, regardless of whether she currently acknowledges problematic substance use. She describes pronounced enjoyment of excitement, risk-taking, and intense experiences. Her approach to life emphasizes spontaneity and immediate gratification rather than planning or consideration of consequences. She reports significant history of behavioral problems, authority conflicts, or legal difficulties beginning in adolescence or earlier. Her social style is characterized by gregariousness, extraversion, and enjoyment of social dominance. She demonstrates poor frustration tolerance with tendency toward impulsive action when desires are thwarted. She reports substantial difficulty managing negative emotional states without external regulation. This constellation of traits creates substantial vulnerability to developing problematic substance use patterns, particularly in environments where substances are readily available."
    },
    "MDS": {
        "low": "This female reports a generally satisfying marital relationship with normal variations in closeness and conflict. She describes effective communication patterns that allow for resolution of disagreements without persistent resentment. She reports mutual respect and appreciation between partners despite awareness of each other's flaws. She describes appropriate balance of togetherness and autonomy within the relationship. Sexual satisfaction is generally positive though may fluctuate with life circumstances. She reports shared decision-making processes that consider both partners' preferences and needs. Financial management shows reasonable agreement about priorities and spending patterns. The relationship demonstrates resilience with capacity to adapt to changing circumstances and recover from occasional conflicts.",
        "moderate": "This female reports increasing marital dissatisfaction that is creating strain though not yet threatening the relationship's viability. She describes communication difficulties with growing patterns of criticism, defensiveness, or withdrawal during conflicts. She reports diminishing expressions of appreciation between partners with greater focus on frustrations and disappointments. She describes increasing emotional distance with less sharing of personal thoughts and feelings. Sexual satisfaction has declined significantly, creating additional relationship tension. She reports more frequent disagreements about decision-making, financial management, or parenting approaches. The relationship shows decreasing resilience with longer recovery periods needed after conflicts and less effective adaptation to changing circumstances.",
        "high": "This female reports severe marital distress that significantly impacts her well-being and may threaten the relationship's continuation. She describes profound communication breakdown characterized by contempt, criticism, defensiveness, and stonewalling. Mutual respect and appreciation are largely absent, replaced by resentment and blame. Emotional distance is pronounced, with minimal sharing of personal experiences or affection. Sexual dissatisfaction is typically severe and contributes to further alienation. Disagreements about critical life areas are frequent, intense, and often unresolved, leading to ongoing conflict or disengagement. The relationship lacks resilience, with partners unable to recover from disputes or adapt constructively to challenges. She likely feels trapped, hopeless, or actively considering separation or divorce."
    }
    // ... other scales like Ho, O-H, Do, Re, Mt, GM, GF, PK, PS would follow,
    // but using only the visible part from the previous truncated output.
};

var SUPPLEMENTARY_SCALES_MALE_JS = {
    "A": {
        "low": "This male reports minimal anxiety symptoms, with appropriate stress responses that return to baseline when stressors diminish. He maintains effective coping strategies for managing routine life challenges without becoming overwhelmed. His thought patterns remain balanced, considering potential problems without catastrophizing or excessive rumination. Daily functioning across work, relationships, and self-care continues unimpaired by anxiety.",
        "moderate": "This male reports moderately elevated anxiety that occasionally interferes with optimal functioning. He experiences periodic excessive worry that persists beyond appropriate time frames and may be difficult to control. Physical symptoms of anxiety such as muscle tension, sleep disruption, or concentration difficulties are becoming more frequent. While still managing major responsibilities, his anxiety is beginning to create strain in relationships and diminish enjoyment of previously pleasurable activities.",
        "high": "This male reports severe anxiety that significantly impairs his functioning across multiple domains. He experiences persistent, uncontrollable worry that consumes substantial mental energy and interferes with concentration and decision-making. Physical manifestations of anxiety are pronounced, potentially including panic attacks, persistent muscle tension, gastrointestinal distress, and significant sleep disruption. His anxiety has led to avoidance of anxiety-provoking situations, substantially restricting his activities and relationships. The chronic nature of his anxiety has likely contributed to secondary depression, fatigue, and irritability."
    },
    "R": {
        "low": "This male demonstrates minimal psychological defensiveness, with willingness to acknowledge both positive and negative aspects of his experience. He readily admits to normal human flaws, insecurities, and negative emotions without excessive shame or guardedness. His self-description includes appropriate recognition of personal limitations and mistakes. He shows psychological-mindedness with capacity to reflect on his own motives, emotions, and patterns.",
        "moderate": "This male shows increasing psychological defensiveness and diminished awareness of his own emotional processes. He demonstrates selective attention to positive aspects of experience while minimizing or disavowing negative emotions, particularly anger and resentment. His self-description emphasizes virtues and strengths with limited acknowledgment of normal human flaws or mistakes. He shows growing reluctance to engage in psychological introspection, preferring concrete explanations for emotional or interpersonal difficulties.",
        "high": "This male demonstrates pronounced psychological defensiveness that significantly limits his self-awareness and capacity for growth. He shows marked inability to recognize or acknowledge negative emotions, particularly anger, resentment, or sexual feelings that conflict with his self-concept as virtuous and proper. His self-description is highly idealized and lacks the normal human flaws or struggles that create authentic self-portraiture. He demonstrates concrete thinking with minimal psychological-mindedness or introspective capacity. When faced with emotional or interpersonal difficulties, he typically externalizes responsibility or focuses exclusively on physical explanations. This defensive structure significantly impairs his ability to engage productively in psychotherapy or make meaningful psychological changes."
    },
    "Es": {
        "low": "This male demonstrates limited psychological resources for managing stress and maintaining stability during challenges. He shows poor frustration tolerance with tendency to become overwhelmed by moderate stressors. His coping strategies are often maladaptive or insufficient for effective problem resolution. He demonstrates limited capacity for delayed gratification or sustained effort toward long-term goals. His self-concept lacks coherence and stability across different contexts. His relationships show patterns of dependency with difficulty maintaining appropriate boundaries. His emotional regulation is poor, with disproportionate reactions to minor provocations and difficulty returning to baseline after upset.",
        "moderate": "This male demonstrates adequate psychological resources for managing routine stressors, though may become overwhelmed during periods of significant challenge. He shows reasonable frustration tolerance for everyday difficulties but may resort to less adaptive coping when facing major stressors. His coping strategies are generally effective for common problems but may be insufficient for complex or chronic difficulties. He can delay gratification for moderate periods to achieve important goals. His self-concept shows basic coherence though may fluctuate somewhat across contexts. His relationships demonstrate general stability with occasional boundary issues during stress. His emotional regulation is adequate for routine interactions though may deteriorate during significant conflict or crisis.",
        "high": "This male demonstrates robust psychological resources for managing stress and maintaining stability even during significant challenges. He shows excellent frustration tolerance with capacity to persist through substantial obstacles toward valued goals. His coping strategies are diverse, flexible, and generally adaptive across various types of problems. He demonstrates strong capacity for delayed gratification in service of meaningful long-term objectives. His self-concept shows coherence and stability across different contexts while maintaining appropriate flexibility. His relationships demonstrate healthy interdependence with clear but permeable boundaries. His emotional regulation is well-developed, with proportionate reactions to provocations and efficient return to baseline after legitimate upset."
    },
    "MAC-R": {
        "low": "This male reports minimal risk factors associated with substance abuse vulnerability. He describes himself as conventional, cautious, and restrained in his approach to pleasure and excitement. He demonstrates strong impulse control and consideration of consequences before acting. His social relationships are characterized by stability rather than gregariousness or risk-taking. He reports minimal history of behavioral problems, authority conflicts, or legal difficulties. His approach to life emphasizes planning, responsibility, and adherence to social norms rather than spontaneity or thrill-seeking.",
        "moderate": "This male shows some personality characteristics associated with increased substance abuse vulnerability, though not at the level typically seen in diagnosed substance use disorders. He describes greater enjoyment of excitement, novelty, and social engagement than the average person. His impulse control is adequate for major decisions but may lapse with smaller temptations. He acknowledges occasional regret following impulsive decisions yet continues similar patterns. While generally functioning within acceptable parameters, his growing prioritization of immediate gratification over long-term consequences may create vulnerability to problematic substance use patterns, particularly in high-risk environments or during periods of significant stress.",
        "high": "This male demonstrates a personality profile strongly associated with substance abuse vulnerability, regardless of whether he currently acknowledges problematic substance use. He describes pronounced enjoyment of excitement, risk-taking, and intense experiences. His approach to life emphasizes spontaneity and immediate gratification rather than planning or consideration of consequences. He reports significant history of behavioral problems, authority conflicts, or legal difficulties beginning in adolescence or earlier. His social style is characterized by gregariousness, extraversion, and enjoyment of social dominance. He demonstrates poor frustration tolerance with tendency toward impulsive action when desires are thwarted. This constellation of traits creates substantial vulnerability to developing problematic substance use patterns, particularly in environments where substances are readily available."
    },
    "AAS": {
        "low": "This male explicitly denies problematic substance use or associated consequences. He reports minimal or no consumption of alcohol or other substances. He denies experiencing tolerance, withdrawal symptoms, or loss of control over substance use. He reports no substance-related interference with major life roles or responsibilities. He denies using substances to manage negative emotions or physical discomfort. He reports no concerns from others about his substance use patterns. He denies engagement in illegal activities related to substance acquisition or use.",
        "moderate": "This male acknowledges some problematic aspects of his substance use while minimizing or rationalizing others. He reports regular substance use that occasionally exceeds his intended limits. He acknowledges some tolerance development though may attribute this to normal adaptation rather than problematic use. He reports occasional interference with responsibilities or relationships due to substance use or recovery from use. He acknowledges sometimes using substances to manage negative emotions or physical discomfort. He reports some expressions of concern from others about his substance use patterns, though typically disagrees with their assessment. He may acknowledge occasional engagement in risky behaviors while using substances.",
        "high": "This male explicitly acknowledges significant problematic substance use and associated consequences. He reports regular substance use that frequently exceeds intended limits with difficulty controlling amount or frequency once started. He acknowledges pronounced tolerance requiring increasing amounts for desired effects. He reports significant interference with major life roles including work performance, relationship quality, or financial stability. He acknowledges regular use of substances to manage negative emotions or physical discomfort. He reports persistent concerns from others about his substance use patterns. He may acknowledge engagement in illegal activities related to substance acquisition or use. This level of acknowledgment typically indicates awareness of a substance use disorder requiring intervention, though not necessarily readiness for treatment."
    },
    "APS": {
        "low": "This male demonstrates minimal personality risk factors associated with substance abuse vulnerability. He describes himself as conventional, cautious, and restrained in his approach to pleasure and excitement. He demonstrates strong impulse control and consideration of consequences before acting. His social relationships are characterized by stability rather than gregariousness or risk-taking. He reports minimal history of behavioral problems, authority conflicts, or legal difficulties. His approach to life emphasizes planning, responsibility, and adherence to social norms rather than spontaneity or thrill-seeking. He acknowledges normal human emotions without excessive need to escape or modify his feeling states.",
        "moderate": "This male shows some personality characteristics associated with increased substance abuse vulnerability, though not at the level typically seen in diagnosed substance use disorders. He describes greater enjoyment of excitement, novelty, and social engagement than the average person. His impulse control is adequate for major decisions but may lapse with smaller temptations. He acknowledges occasional regret following impulsive decisions yet continues similar patterns. He reports some difficulty tolerating negative emotional states, creating potential motivation to use substances for emotional regulation. While generally functioning within acceptable parameters, his personality profile suggests increased vulnerability to developing problematic substance use patterns, particularly in high-risk environments or during periods of significant stress.",
        "high": "This male demonstrates a personality profile strongly associated with substance abuse vulnerability, regardless of whether he currently acknowledges problematic substance use. He describes pronounced enjoyment of excitement, risk-taking, and intense experiences. His approach to life emphasizes spontaneity and immediate gratification rather than planning or consideration of consequences. He reports significant history of behavioral problems, authority conflicts, or legal difficulties beginning in adolescence or earlier. His social style is characterized by gregariousness, extraversion, and enjoyment of social dominance. He demonstrates poor frustration tolerance with tendency toward impulsive action when desires are thwarted. He reports substantial difficulty managing negative emotional states without external regulation. This constellation of traits creates substantial vulnerability to developing problematic substance use patterns, particularly in environments where substances are readily available."
    },
    "MDS": {
        "low": "This male reports a generally satisfying marital relationship with normal variations in closeness and conflict. He describes effective communication patterns that allow for resolution of disagreements without persistent resentment. He reports mutual respect and appreciation between partners despite awareness of each other's flaws. He describes appropriate balance of togetherness and autonomy within the relationship. Sexual satisfaction is generally positive though may fluctuate with life circumstances. He reports shared decision-making processes that consider both partners' preferences and needs. Financial management shows reasonable agreement about priorities and spending patterns. The relationship demonstrates resilience with capacity to adapt to changing circumstances and recover from occasional conflicts.",
        "moderate": "This male reports increasing marital dissatisfaction that is creating strain though not yet threatening the relationship's viability. He describes communication difficulties with growing patterns of criticism, defensiveness, or withdrawal during conflicts. He reports diminishing expressions of appreciation between partners with greater focus on frustrations and disappointments. He describes increasing emotional distance with less sharing of personal thoughts and feelings. Sexual satisfaction has declined significantly, creating additional relationship tension. He reports more frequent disagreements about decision-making, financial management, or parenting approaches. The relationship shows decreasing resilience with longer recovery periods needed after conflicts and less effective adaptation to changing circumstances.",
        "high": "This male reports severe marital distress that significantly impacts his well-being and may threaten the relationship's continuation. He describes profound communication breakdown characterized by contempt, criticism, defensiveness, and stonewalling. Mutual respect and appreciation are largely absent, replaced by resentment and blame. Emotional distance is pronounced, with minimal sharing of personal experiences or affection. Sexual dissatisfaction is typically severe and contributes to further alienation. Disagreements about critical life areas are frequent, intense, and often unresolved, leading to ongoing conflict or disengagement. The relationship lacks resilience, with partners unable to recover from disputes or adapt constructively to challenges. He likely feels trapped, hopeless, or actively considering separation or divorce."
    }
    // ... other scales like Ho, O-H, Do, Re, Mt, GM, GF, PK, PS would follow,
    // but using only the visible part from the previous truncated output.
};
