"""
MMPI-2 Component Scale Interpretations

This module provides detailed interpretations for MMPI-2 Component Scales
based on T-score ranges and gender.
"""

# Component Scale Interpretations Dictionary
COMPONENT_SCALE_INTERPRETATIONS = {
    "Female": {
        # Anxiety (ANX) Component Scales
        "ANX1": {  # Generalized Anxiety
            "low": "This female reports anxiety levels within normal limits. She experiences occasional worry appropriate to life circumstances that resolves when situations improve. Physiological arousal remains appropriate to contextual demands, with normal stress responses that return to baseline when stressors diminish. She maintains effective coping strategies for managing routine life challenges without becoming overwhelmed. Sleep is generally restorative with occasional difficulty falling asleep during stressful periods but without persistent disruption. Her thought patterns remain balanced, considering potential problems without catastrophizing or excessive rumination. Daily functioning across work, relationships, and self-care continues unimpaired by anxiety. She can typically relax during leisure time without intrusive worry. When faced with uncertainty, she experiences appropriate concern without becoming paralyzed by indecision or worst-case scenario thinking. Her anxiety serves an adaptive function, motivating preparation and appropriate caution without creating significant distress or functional impairment.",
            
            "moderate": "This female reports moderately elevated anxiety that occasionally interferes with optimal functioning. She experiences periodic excessive worry that persists beyond appropriate time frames and may be difficult to control through typical coping strategies. Physiological symptoms of anxiety such as muscle tension, restlessness, or autonomic arousal occur with sufficient frequency or intensity to create noticeable discomfort without severely disrupting daily activities. Sleep may be affected by difficulty falling asleep due to racing thoughts or worry about upcoming events, though not to degree that creates severe sleep deprivation or daytime impairment. Concentration occasionally suffers when worry intrudes on task focus, requiring additional effort to maintain productivity. Some avoidance of anxiety-provoking situations may occur, though not to extent that significantly restricts life activities or creates obvious impairment. Perfectionism or excessive concern about mistakes may emerge in some contexts, creating unnecessary revision or delay without completely preventing task completion. While generally maintaining daily functioning across domains, she expends additional energy managing anxiety that could otherwise be directed toward more productive or pleasurable activities. This moderate anxiety creates subjective distress without severely compromising functioning, potentially responding well to targeted intervention addressing specific worry content and developing more effective anxiety management strategies.",
            
            "high": "This female reports significantly elevated anxiety that substantially interferes with optimal functioning across multiple domains. She experiences persistent, excessive worry that proves difficult to control despite active attempts, with anxiety continuing beyond appropriate timeframes and often focusing on minor matters or worst-case scenarios unlikely to occur. Physiological symptoms of anxiety are pronounced, potentially including muscle tension, restlessness, fatigue, concentration difficulties, irritability, and sleep disturbance that create significant discomfort and functional impairment. Autonomic arousal may produce racing heart, sweating, shortness of breath, dizziness, or other physical manifestations that create additional worry about health or embarrassment in social situations. Sleep is significantly disrupted by difficulty falling asleep due to racing thoughts or physical tension, with possible middle-of-night awakening and difficulty returning to sleep, creating daytime fatigue that further compromises functioning. Concentration suffers markedly when worry intrudes on task focus, reducing productivity and potentially creating occupational or academic consequences. Perfectionism or excessive concern about mistakes may create significant delay or avoidance of tasks where evaluation might occur, limiting performance despite adequate knowledge or skill. Decision-making is compromised by fear of making wrong choices, creating either paralysis or impulsive decisions to escape the discomfort of uncertainty, neither pattern producing optimal outcomes. Avoidance of anxiety-provoking situations may significantly restrict life activities, creating obvious impairment in social, occupational, or other important areas of functioning. While maintaining awareness that her worry is excessive, she experiences limited control over the process once triggered, creating sense of helplessness that may contribute to secondary depression. This significant anxiety creates both subjective distress and objective functional impairment, likely meeting diagnostic criteria for an anxiety disorder and warranting targeted intervention."
        },
        
        "ANX2": {  # Phobic Anxiety
            "low": "This female reports minimal specific fears or phobic anxiety, with appropriate caution in genuinely dangerous situations but without excessive fear responses to objectively safe circumstances. She navigates public spaces, transportation systems, crowds, heights, enclosed spaces, and other common phobic triggers without significant distress or avoidance behaviors. When encountering potentially threatening situations, she evaluates risk realistically rather than catastrophizing potential outcomes or overestimating danger probability. If mild anxiety occurs in specific contexts, she manages it effectively without requiring escape or safety behaviors that would reinforce fear responses. Social situations are approached with normal caution rather than excessive concern about evaluation or embarrassment. Medical procedures or natural phenomena like storms generate appropriate preparation without overwhelming fear or elaborate avoidance strategies. This absence of phobic anxiety allows flexible engagement with diverse environments and experiences without restriction based on irrational fears.",
            
            "moderate": "This female reports moderately elevated specific fears that create noticeable distress without severely restricting daily functioning. She experiences heightened anxiety in particular situations such as heights, enclosed spaces, public transportation, crowds, or specific animals/insects, recognizing these fears as somewhat excessive while maintaining some ability to manage them when necessary. Anticipatory anxiety occurs when expecting to encounter phobic triggers, creating additional distress beyond the actual exposure situation. Some avoidance of fear-inducing circumstances occurs when possible without major life disruption, such as taking stairs instead of elevators or driving rather than flying for manageable distances. When avoidance is impossible due to practical necessities, she endures phobic situations with significant discomfort, potentially utilizing safety behaviors such as medication, distraction techniques, or accompaniment by trusted others to manage anxiety. Physical symptoms of fear such as increased heart rate, sweating, or muscle tension occur during phobic exposure but typically remain below panic intensity. While generally maintaining essential activities despite these fears, she expends additional energy managing anxiety that could otherwise be directed toward more productive or pleasurable experiences. This moderate phobic anxiety creates subjective distress without severely compromising functioning, potentially responding well to targeted exposure-based interventions addressing specific fear triggers.",
            
            "high": "This female reports significantly elevated specific fears that substantially interfere with normal functioning through intense distress and extensive avoidance behaviors. She experiences overwhelming anxiety when confronted with particular situations or objects such as heights, enclosed spaces, public transportation, crowds, specific animals/insects, storms, or medical procedures, with fear recognized as grossly excessive relative to actual danger but experienced as beyond voluntary control. Anticipatory anxiety begins well before potential exposure, creating significant distress that may include sleep disruption, concentration problems, or physical symptoms even when the feared situation is not imminent but merely anticipated in future. Avoidance of fear-inducing circumstances is extensive, creating significant life restrictions such as inability to travel by air, use elevators even in tall buildings, attend crowded events regardless of importance, or receive necessary medical care due to procedure anxiety. When avoidance is impossible due to absolute necessity, endurance of phobic situations produces intense distress potentially reaching panic levels, with physical symptoms including racing heart, shortness of breath, sweating, trembling, dizziness, and fears of losing control or experiencing medical emergency. Safety behaviors such as medication, distraction techniques, or requiring accompaniment by trusted others become necessary rather than optional, creating dependence that further reinforces fear and prevents natural habituation. The individual recognizes the fear as excessive or unreasonable but feels powerless to modify the response through rational understanding alone, creating sense of being controlled by the phobia rather than managing it effectively. This significant phobic anxiety creates both subjective distress and objective functional impairment through the combination of intense fear responses and extensive avoidance behaviors, likely meeting diagnostic criteria for specific phobia and warranting targeted intervention using exposure-based approaches."
        },
        
        "ANX3": {  # Worry/Rumination
            "low": "This female reports worry and rumination within normal limits, with thought patterns that remain appropriately balanced between problem-solving consideration and mental disengagement when solutions are unavailable. She experiences occasional worry about legitimate concerns that resolves when situations improve or effective coping strategies are implemented. When facing uncertainty, she considers potential outcomes without becoming fixated on worst-case scenarios or engaging in catastrophic thinking that magnifies threat perception beyond realistic probabilities. Past mistakes or embarrassing incidents are processed appropriately without excessive mental review that extracts no new insights while perpetuating negative emotions. Decision-making proceeds efficiently without paralyzing doubt or endless reconsideration of choices already made. Sleep remains generally unaffected by racing thoughts or worry, allowing restorative rest that supports daytime functioning. When worrisome thoughts do arise, she demonstrates ability to redirect attention to present-moment experience or productive activities rather than becoming trapped in circular thinking patterns. This balanced cognitive approach allows appropriate preparation for potential problems without creating unnecessary distress about circumstances beyond control.",
            
            "moderate": "This female reports moderately elevated worry and rumination that create noticeable mental preoccupation without completely dominating thought content. She experiences persistent concern about future events that extends beyond appropriate preparation timeframes, with difficulty disengaging from worry even when no productive problem-solving is occurring. When facing uncertainty, she tends toward anticipating negative outcomes with greater frequency or intensity than positive possibilities, creating pessimistic outlook that magnifies threat perception beyond realistic probabilities. Past mistakes or embarrassing incidents receive excessive mental review without extracting new insights, perpetuating negative emotions through repeated rehearsal of distressing memories. Decision-making involves considerable doubt and excessive consideration of potential negative consequences, creating delay or discomfort though not completely preventing choices from being made. Sleep may be affected by racing thoughts or worry at bedtime, creating occasional difficulty falling asleep though not severe insomnia that significantly impairs daytime functioning. When worrisome thoughts arise, she demonstrates limited ability to redirect attention, becoming temporarily trapped in circular thinking patterns before eventually disengaging through deliberate effort or external distraction. While maintaining basic functioning across domains, mental energy is partially consumed by these unproductive thought patterns, reducing cognitive resources available for more constructive or enjoyable activities. This moderate rumination creates subjective distress without severely compromising functioning, potentially responding well to targeted cognitive interventions addressing thought patterns and developing more effective mental disengagement strategies.",
            
            "high": "This female reports significantly elevated worry and rumination that substantially interfere with mental well-being and functional capacity across multiple domains. She experiences persistent, intrusive worry about future events that dominates thought content despite recognition of its unproductive nature, with inability to disengage from circular thinking patterns even when causing significant distress and no problem-solving benefit. When facing uncertainty, she engages in catastrophic thinking that focuses almost exclusively on worst-case scenarios while discounting more probable neutral or positive outcomes, creating severely distorted threat perception that magnifies risks beyond realistic probabilities. Past mistakes, embarrassing incidents, or perceived failures receive obsessive mental review without extracting new insights, perpetuating and intensifying negative emotions through endless rehearsal that prevents emotional processing and resolution. Decision-making is severely compromised by paralyzing doubt and excessive consideration of potential negative consequences, creating either avoidance of choices or significant distress following decisions due to persistent second-guessing and regret regardless of outcome quality. Sleep is significantly disrupted by racing thoughts or worry at bedtime, with difficulty falling asleep and possible middle-of-night awakening with immediate return to rumination, creating sleep deprivation that further compromises cognitive functioning and emotion regulation. When worrisome thoughts arise, she demonstrates minimal ability to redirect attention, becoming trapped in circular thinking patterns that may persist for hours without effective disengagement strategies. Mental energy is substantially consumed by these unproductive thought patterns, severely reducing cognitive resources available for problem-solving, relationship engagement, or enjoyment of previously pleasurable activities. This significant rumination creates both subjective distress and objective functional impairment, likely contributing to or maintaining depression and anxiety disorders while requiring targeted cognitive interventions to interrupt established mental habits and develop more effective thought management strategies."
        },
        
        # Social Discomfort (SOD) Component Scales
        "SOD2": {  # Shyness
            "high": "This female reports significant social anxiety that substantially interferes with interpersonal functioning and cr
(Content truncated due to size limit. Use line ranges to read in chunks)
