"""
PSY-5 Scales Interpretations for the MMPI-2.

This module provides detailed interpretations for the PSY-5 Scales
of the MMPI-2, with specific narratives for different T-score ranges and gender.
"""

# PSY-5 Scales interpretations for females
PSY5_SCALES_FEMALE = {
    "AGGR": {
        "low": "This woman demonstrates a cooperative, accommodating interpersonal style. She avoids confrontation and prioritizes harmony in relationships. She typically defers to others in decision-making and rarely asserts her own preferences when they conflict with others'. She describes discomfort with expressing anger or disagreement directly. Her self-description emphasizes being agreeable, kind, and easy to get along with. She reports minimal competitive drive and prefers collaborative rather than individual achievement. In conflict situations, she tends toward compromise or acquiescence rather than standing firm on her position. Her relationships are characterized by minimal assertiveness and high accommodation of others' needs and preferences.",
        
        "moderate": "This woman is showing a more balanced approach to assertiveness and accommodation in relationships. She can express her preferences and stand up for her needs when important, while still valuing harmony and cooperation. She describes appropriate competitive drive in achievement contexts without excessive aggression. She acknowledges feeling angry when legitimately wronged and can express this emotion in constructive ways. Her decision-making considers both her own needs and others' perspectives. In conflict situations, she can advocate for her position while remaining open to compromise. Her relationships demonstrate a healthy balance between self-assertion and consideration for others, without significant domination or submission patterns.",
        
        "high": "This woman demonstrates a highly assertive, dominant interpersonal style that can cross into aggressiveness. She readily expresses anger and confronts others when displeased. She describes strong competitive drive and desire to win or achieve dominance in various contexts. Her decision-making prioritizes her own preferences with less consideration of others' needs or wishes. She acknowledges enjoying positions of power and influence over others. In conflict situations, she stands firm on her position and may become intimidating or forceful to prevail. Her relationships show patterns of dominance, with others often deferring to her stronger personality. While she can be an effective leader in situations requiring decisive action, her forceful style may create interpersonal difficulties when collaboration or sensitivity is needed."
    },
    
    "PSYC": {
        "low": "This woman maintains conventional perceptions and thought processes without unusual experiences or beliefs. Her thinking remains logical and reality-based across various contexts. She doesn't report unusual sensory experiences or perceptual distortions. Her beliefs align with cultural norms without idiosyncratic or magical elements. She maintains clear boundaries between imagination and reality. Her emotional responses remain proportionate and appropriate to situations. She doesn't describe experiences of depersonalization, derealization, or other unusual subjective phenomena. Her narrative remains coherent and goal-directed without tangentiality or loosening of associations.",
        
        "moderate": "This woman is beginning to experience some unusual cognitive or perceptual phenomena that she finds intriguing or concerning. She describes occasional experiences that suggest mild reality distortion, such as heightened sensory sensitivity, illusions, or brief dissociative episodes. Her thinking sometimes becomes more tangential or circumstantial, particularly under stress. She reports some magical thinking or unusual beliefs that she recognizes may not be shared by others. She describes occasional feelings of unreality or detachment from herself or her environment. Her interpersonal boundaries may become temporarily blurred in certain contexts. While generally maintaining adequate reality testing, she acknowledges these experiences as unusual and potentially meaningful, creating some curiosity or concern about her psychological processes.",
        
        "high": "This woman's experience is characterized by significant psychotic processes that substantially alter her perception of reality. She describes unusual sensory experiences such as hearing voices, seeing visions, or feeling unusual bodily sensations that suggest external influence. Her thinking shows marked peculiarity, with loose associations, tangentiality, or unusual logic that others find difficult to follow. She reports beliefs or ideas that have magical, referential, or delusional qualities, often expressed with conviction despite lack of conventional evidence. She describes significant experiences of depersonalization or derealization that create a profound sense of disconnection from herself or her environment. Her narrative often includes themes of special abilities, unusual sensitivities, or experiences that set her apart from others. These psychotic processes significantly impair her ability to maintain consistent reality testing and compromise her functioning across multiple domains."
    },
    
    "DISC": {
        "low": "This woman demonstrates strong adherence to social norms and conventional expectations. She describes a developmental history without significant behavioral problems or authority conflicts. Her narrative emphasizes responsibility, reliability, and consideration for rules and others' rights. She makes decisions with careful consideration of potential consequences and ethical implications. She demonstrates effective impulse control and can delay gratification appropriately. Her approach to life emphasizes planning, caution, and consistency rather than spontaneity or risk-taking. She reports minimal experimentation with substances or other boundary-pushing behaviors. Her relationships and work history show stability, dependability, and follow-through on commitments.",
        
        "moderate": "This woman is showing increased impulsivity and risk-taking behavior that sometimes exceeds prudent boundaries. She describes making more decisions based on immediate desires with less consideration of potential negative consequences. Her adherence to social norms is becoming more selective, with greater willingness to bend rules when they conflict with personal desires. She reports increased enjoyment of novel, exciting experiences even when they involve moderate risk. Her substance use may be increasing in frequency or intensity. She acknowledges a pattern of occasional regret following impulsive decisions yet continues to act without adequate forethought in many situations. While still functioning within broadly acceptable parameters, her growing prioritization of immediate gratification over long-term consequences is creating recurring problems in relationships and personal responsibilities.",
        
        "high": "This woman's experience and behavior are characterized by profound disconstraint that significantly disrupts her functioning across domains. She describes persistent difficulty controlling impulses, with actions frequently driven by immediate desires without consideration of consequences. Her decision-making shows a pattern of high-risk choices in areas including finances, substances, sexual behavior, and personal safety. She reports intense boredom with routine and constant seeking of novel, stimulating experiences regardless of potential danger. She describes minimal anxiety about engaging in illegal or socially prohibited behaviors, viewing rules as arbitrary constraints that don't apply to her. Her substance use typically shows escalation beyond recreational patterns. Her narrative includes numerous examples of actions taken with full awareness of likely negative consequences yet inability to inhibit the behavior. This pervasive disconstraint has typically resulted in significant adverse outcomes including legal problems, unstable relationships, financial difficulties, and compromised health or safety. Despite these repeated negative consequences, she struggles to modify her impulsive behavior patterns, creating a chaotic and unstable life trajectory."
    },
    
    "NEGE": {
        "low": "This woman experiences negative emotions within normal parameters of frequency, intensity, and duration. She recovers from emotional upsets within reasonable timeframes without prolonged disruption. She maintains perspective during stressful circumstances without catastrophizing. Her reactions to criticism are proportionate without excessive sensitivity. She experiences normal anxieties but these don't significantly interfere with functioning. Her emotional responses are generally predictable and appropriate to situations. She demonstrates resilience following setbacks rather than prolonged distress. Her self-description doesn't emphasize emotional vulnerability or instability as defining characteristics.",
        
        "moderate": "This woman is experiencing increasing emotional reactivity and negative emotionality that is beginning to affect her well-being. She describes more intense and prolonged responses to stressors that are becoming difficult to regulate. Her threshold for emotional upset is lowering, with minor frustrations triggering disproportionate reactions. She reports greater sensitivity to criticism, with perceived slights leading to lingering hurt feelings. Her worry about potential problems is increasing, with a tendency toward anxious anticipation of negative outcomes. She acknowledges spending more mental energy managing emotional distress, which is becoming exhausting. While still functioning in major life roles, the growing intensity and persistence of negative emotions is creating strain in her relationships and diminishing her enjoyment of previously pleasurable activities.",
        
        "high": "This woman's subjective experience is dominated by overwhelming, persistent negative emotions that significantly impair her functioning. She describes extreme emotional reactivity, with intense distress triggered by minor stressors that others would manage easily. Her emotional recovery is profoundly impaired, with negative emotional states persisting for days or weeks after triggering events. She reports extreme sensitivity to criticism or rejection, experiencing devastating emotional pain from perceived slights. Her thought processes are characterized by catastrophic interpretations and automatic negative predictions. She describes her emotional experience as overwhelming and uncontrollable, leaving her feeling constantly vulnerable and insecure. This pervasive negative emotionality has led to significant avoidance of potentially triggering situations, substantially narrowing her life experience. Her relationships are strained by the burden of her emotional intensity and need for reassurance. Despite understanding the disproportionate nature of her emotional reactions, she feels powerless to modulate them, creating a debilitating pattern of emotional dysregulation that dominates her daily experience."
    },
    
    "INTR": {
        "low": "This woman demonstrates normal social engagement and capacity for positive emotional experiences. She initiates and maintains social connections without significant discomfort. She describes genuine enjoyment from various activities and relationships. Her emotional range includes frequent positive states such as joy, enthusiasm, and interest. She seeks out social interaction for its inherent pleasure rather than solely for instrumental purposes. Her energy is appropriately invested in pursuing rewarding experiences and relationships. She anticipates future events with appropriate positive expectation. Her affect during interviews shows normal animation and expression of positive emotion when discussing pleasant topics.",
        
        "moderate": "This woman is showing increased social detachment and diminished capacity for positive emotional experiences. She describes less interest in social interaction and growing preference for solitary activities. Her emotional responses to typically enjoyable events are becoming more muted, with fewer experiences of genuine enthusiasm or joy. She reports decreased initiation of social contacts and more perfunctory participation when social engagement is necessary. Her anticipation of future events lacks the element of positive excitement that was previously present. Her affect during interviews shows less spontaneous animation, with fewer natural smiles or expressions of positive emotion. While still maintaining necessary social functions, she acknowledges a growing sense of detachment from others and diminished capacity for pleasure that is beginning to concern her.",
        
        "high": "This woman's experience is characterized by profound social detachment and a pervasive inability to experience positive emotions. She describes complete absence of desire for social connection, viewing relationships as burdensome obligations rather than sources of pleasure. Her emotional landscape is marked by anhedonia, with no activities, achievements, or interactions generating genuine enjoyment or enthusiasm. She reports no anticipatory pleasure for future events and cannot imagine experiencing authentic happiness. Her affect is notably flat and constricted, with an absence of spontaneous positive expressions even when discussing objectively positive topics. She has abandoned previously enjoyed activities as they no longer provide any sense of satisfaction. She describes herself as fundamentally different from others who seem capable of connection and joy. This profound deficit in social engagement and positive emotionality has led to an isolated existence characterized by mechanical fulfillment of necessary functions without authentic engagement or pleasure, significantly impairing her quality of life despite often adequate practical functioning."
    }
}

# PSY-5 Scales interpretations for males
PSY5_SCALES_MALE = {
    "AGGR": {
        "low": "This man demonstrates a cooperative, accommodating interpersonal style. He avoids confrontation and prioritizes harmony in relationships. He typically defers to others in decision-making and rarely asserts his own preferences when they conflict with others'. He describes discomfort with expressing anger or disagreement directly. His self-description emphasizes being agreeable, kind, and easy to get along with. He reports minimal competitive drive and prefers collaborative rather than individual achievement. In conflict situations, he tends toward compromise or acquiescence rather than standing firm on his position. His relationships are characterized by minimal assertiveness and high accommodation of others' needs and preferences.",
        
        "moderate": "This man is showing a more balanced approach to assertiveness and accommodation in relationships. He can express his preferences and stand up for his needs when important, while still valuing harmony and cooperation. He describes appropriate competitive drive in achievement contexts without excessive aggression. He acknowledges feeling angry when legitimately wronged and can express this emotion in constructive ways. His decision-making considers both his own needs and others' perspectives. In conflict situations, he can advocate for his position while remaining open to compromise. His relationships demonstrate a healthy balance between self-assertion and consideration for others, without significant domination or submission patterns.",
        
        "high": "This man demonstrates a highly assertive, dominant interpersonal style that can cross into aggressiveness. He readily expresses anger and confron
(Content truncated due to size limit. Use line ranges to read in chunks)
